name: Running test on push to main

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python   # Writing name is not necessary
        uses: actions/setup-python@v4   # Whenever something is similar we dont use -
        with:
          python-version: 3.11.5
      - name: Install Dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run Test Cases
        run: pytest test_predictions.py